# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.7.0

jobs:
  one:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - node/install:
          install-yarn: true 
          node-version: '15.6'
      - run: 
          name: 'Print to console'
          command: echo 'Step executed'    

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - one
      
