name: Auto rerun
on:
  workflow_dispatch:

jobs:
   passed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am passed"
   failing:
    runs-on: ubuntu-latest
    steps: 
      - name: first fail
        if: github.run_attempt == 1
        run: exit 1
      - name: second pass
        run: echo "I am passed too"
   report:
     if: always()
     runs-on: ubuntu-latest
     needs: [passed, failing]
     steps:
      - name: jobs
        run: curl -X GET -H "Accept:application/vnd.github+json" -s -u "admin:${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
   rerun:
    if: failure()
    runs-on: ubuntu-latest
    needs: [passed, failing, report]
    steps:
      - name: log env
        run: echo ${{env.failure}}
      - name: rerun
        if: github.run_attempt == 1
        run: curl -X POST -H "Accept:application/vnd.github+json" -H "Content-Type:application/json" -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun_run.yml/dispatches -d '{"ref":"main", "inputs":{"run_id":"${{github.run_id}}"}}'
   mail:
     if: ${{failure() && github.run_attemp > 1}}
     runs-on: ubuntu-latest
     needs: [report, rerun]
     steps: 
       - name: Print
         run: echo "I am sending an email"
      
       
