name: Auto rerun
on:
  workflow_dispatch:

jobs:
   passed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am passed"
   failing:
    runs-on: ubuntu-latest
    steps: 
      - name: first fail
        if: github.run_attempt == 1
        run: exit 1
      - name: second pass
        run: echo "I am passed too"
   rerun:
    if: failure()
    runs-on: ubuntu-latest
    needs: [passed, failing]
    env: 
      failure: ${{failure()}}
    steps:
      - name: log env
        run: echo ${{env.failure}}
      - name: rerun
        run: curl -X POST -H "Accept:application/vnd.github+json" -H "Content-Type:application/json" -s -u "admin:${{ secrets.PAT }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun_run.yml/dispatches -d '{"ref":"main", "inputs":{"run_id":"${{github.run_id}}"}}'
   report:
     runs-on: ubuntu-latest
     needs: [passed, failing]
     steps:
      - name: jobs
        run: curl -X GET -H "Accept:application/vnd.github+json" -s -u "admin:${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
