# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        device: ["iPhone 8", "iPad Pro (12.9-inch) (5th generation)"]
        only: ['-only-testing "EndToEndTests/AwesomeSwiftUITests" -only-testing "EndToEndTests/BeamUITests" -only-testing "EndToEndTests/CalcupadUITests" -only-testing "EndToEndTests/DuckDuckGoUITests" -only-testing "EndToEndTests/HapticHavenUITests" -only-testing "EndToEndTests/NetNewsWireUITests" -only-testing "EndToEndTests/Swift2048UITests" -only-testing "EndToEndTests/SwiftWeatherUITests"','-only-testing "EndToEndTests/TrackMyTimeUITests" -only-testing "EndToEndTests/UnwrapUITests" -only-testing "EndToEndTests/UIKitCatalogUITests" -only-testing "EndToEndTests/WikipediaUITests" -only-testing "EndToEndTests/YoutubeUITests" -only-testing "EndToEndTests/OpenShopUITests"', '-only-testing "EndToEndTests/StocksUITests" -only-testing "EndToEndTests/KickstarterUITests" -only-testing "EndToEndTests/SettingsUITests" -only-testing "EndToEndTests/ContactsUITests" -only-testing "EndToEndTests/HealthUITests" -only-testing "EndToEndTests/CalendarUITests"']
    runs-on: ubuntu-latest
    env:
        Test_Var: ${{ format('{0}_{1}_{2}', github.workflow, github.run_id, github.repository  ) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          chmod +x ./test.sh
          ./test.sh
          env
      - name: Check var
        run: echo $Test_Var
      - name: Check matrix device
        run: echo "${{matrix.device}}"
      - name: Check matrix only
        run: echo "${{matrix.only}}"  


