name: Complex flow 

on:
  workflow_dispatch:


jobs: 
  first-batch:
    runs-on: ubuntu-latest 
    steps:
      - run: | 
         echo "First batch"
         cat /etc/hosts
         echo "_____________________ END __________________________"
         echo "127.0.0.1 test-linux-host" | sudo tee -a /etc/hosts
         cat /etc/hosts

  second-batch:
    runs-on: macos-latest 
    steps:
      - run: | 
         echo "Second batch"  
         cat /etc/hosts
         echo "_____________________ END __________________________"
         echo "127.0.0.1 test-macos-host" | sudo tee -a /etc/hosts
         cat /etc/hosts

  third-batch:
    runs-on: windows-latest 
    steps:
      - run: | 
         echo "Third batch"
         cat C:\Windows\System32\drivers\etc\hosts
         echo "_____________________ END __________________________"
         echo "127.0.0.1 windows.local.test" | tee -a C:\Windows\System32\drivers\etc\hosts
         cat C:\Windows\System32\drivers\etc\hosts
      - uses: actions/checkout@v5
      - run: node test.js
             
