name: Complex flow 

on:
  workflow_dispatch:


jobs: 
  first-batch:
    runs-on: ubuntu-latest 
    steps:
      - run: | 
         echo "First batch"
         unzip --help
  second-batch:
    runs-on: macos-latest 
    steps:
      - run: | 
         echo "Second batch"  
         unzip --help
  third-batch:
    runs-on: ubuntu-latest 
    steps:
      - run: | 
         echo "Third batch"         
             
