
name: EMPTY
on:
  workflow_dispatch:
  
env:
  TEST_VAR: ${{github.run_id}}

jobs:
   empty:
    runs-on: ubuntu-latest
    steps:
      - name: check empty
        run: |
            ls  
            pwd
      - name: checkout
        uses: actions/checkout@v2      
      - name: check cloned
        run:  |
            ls
            pwd
      - name: check test env
        run: echo "TEST_VAR env var >>> $TEST_VAR"
