name: Failure_Run
on:
  workflow_dispatch:

jobs:
   echo:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: ${{failure()}}
    steps:
      - name: check test env
        run: echo "TEST_VAR env var >>> $TEST_VAR"
