name: Failure_Run
on:
  workflow_dispatch:

jobs:
   ff:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
   echo:
    needs: ff
    runs-on: ubuntu-latest
    steps:
      - name: echo if failure
        if: failure()
        run: echo Failured
      - name: echo
        run: echo Test
