
name: GITHUB Env
on:
  workflow_call:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        include:
          - current_env: "Test_1"
          - color: green
    runs-on: ubuntu-latest
    environment: ${{matrix.current_env}}
    env: 
      CHECK: ${{vars.CHECK}}
      secret: ${{secrets.SUPER_SECRET}}
    steps:        
      - run: echo "${{ toJSON(github) }}"
      - run: echo "$CHECK"
      - run: echo ${{matrix.color}}
      - run: echo "$secret"
      - run: echo "${{(github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && 'Manual' || 'Something else' }}"
      - run: java --version
      - run: sudo apt-get install xmlstarlet
      - uses: actions/checkout@v3
        with: 
          ref: ${{github.ref}}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: parse json
        id: parse_json
        run: |
          echo version=$(node -p "require('./test.json').version") >> $GITHUB_OUTPUT
      - run: echo "Using output from previous action ==>:$CURRENT_VAR" 
        env:
          CURRENT_VAR: ${{steps.parse_json.outputs.version}}
          
