
name: Matrix Env
on:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        include:
          - current_env: "Test_1"
          - current_env: "Test_2"
          - color: green
    runs-on: ubuntu-latest
    environment: ${{matrix.current_env}}
    env: 
      CHECK: ${{vars.CHECK}}
    steps:        
      - run: echo "$CHECK"
      - run: echo ${{matrix.color}}
