
name: GITHUB Env
on:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        include:
          - current_env: "Test_1"
          - color: green
    runs-on: ubuntu-latest
    environment: ${{matrix.current_env}}
    env: 
      CHECK: ${{vars.CHECK}}
      secret: ${{secrets.SUPER_SECRET}}
    steps:        
      - run: echo ${{ toJSON(github) }}
      - run: echo "$CHECK"
      - run: echo ${{matrix.color}}
      - run: echo "$secret"
      - run: java --version
