

name: Windows chrome 
on:
  workflow_dispatch:
  
env:
  TEST_VAR: "CHECK_${{github.run_id}}"

jobs:
   empty:
    runs-on: windows-latest
    steps:
      - name: check chrome 
        run: env
        shell: bash
      - name: where chrome
        shell: bash
        run: |
         cd C:\ 
         ls 
