

name: Windows chrome 
on:
  workflow_dispatch:
  
env:
  TEST_VAR: "CHECK_${{github.run_id}}"

jobs:
   empty:
    runs-on: windows-latest
    steps:
      - name: check chrome 
        run: env
        shell: bash
      - name: check chrome 
        run: |
         cmd /c "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --version
