

name: Matrix Container
on:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        include:
          - current_env: alpine
          - current_env: debian
          - color: green
    runs-on: ubuntu-latest
    container: ${{matrix.current_env}}
    steps:        
      - run: |
          cat /etc/os-release
          lsb_release -a
          hostnamectl
      - run: echo ${{matrix.color}}
