
name: Matrix_output
on:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        device: ["first", "second"]
        id: [1, 2]
    outputs:
      format('device_${0}_${1}',  ${{matrix.device}}, ${{matrix.id}}): ${{matrix.device}}
    runs-on: ubuntu-latest
    steps:        
      - name: Run matrix name
        id: device
        run: echo echo "::set-output name=device${{matrix.id}}::${{matrix.device}}"
   id:
     runs-on: ubuntu-latest
     needs: matrix
     steps:
      - name: print
        run: echo "${{toJSON(needs)}}"
