
name: Matrix_output
on:
  workflow_dispatch:

jobs:
   matrix:
    strategy:
      matrix:
        device: ["first", "second"]
        id: [1, 2]
    runs-on: ubuntu-latest
    steps:        
      - name: Run matrix name
        id: device
        run: echo echo "::set-output name=device${{matrix.id}}::${{matrix.device}}"
   id:
     runs-on: ubuntu-latest
     needs: matrix
     steps:
      - name: print
        run: $(curl -X GET -s -u "admin:${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
