name: GITHUB Needs status
on:
  workflow_call:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:        
      - run: exit 1
  first1:
    runs-on: ubuntu-latest
    steps:        
      - run: echo "${{toJSON(github.event_name)}}"
  second: 
    if: always()
    needs: [first, first1]
    runs-on: ubuntu-latest
    steps:
     - run: echo ${{needs.first.result}}
     - run: echo ${{needs.first1.result}}
      
