name: REPORT

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        code: [1, 0, 0]
    steps:
      - name: Run a one-line script
        run: echo  Code [${{matrix.code}}]
      - name: Set job code
        run: exit ${{matrix.code}}
   running:
    strategy:
      matrix:
        code: [0, 0, 0]
    runs-on: ubuntu-latest
    steps:        
      - name: Run a one-line script
        run: echo  Code [${{matrix.code}}]
      - name: Set job code
        run: exit ${{matrix.code}}
   report:
    if: ${{failure()}}
    needs: [running, checking]
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting a failure
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
    # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
    # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
          subject: Report from ${{ github.repository }} has failed job
    # email body as text
          body: Worflow ${{ github.workflow }} of ${{ github.repository }} has \n
                asdasdasdkiadas \n
                last line
          html_body: file://report_support.html
    # comma-separated string, send email to
          to: tranduil15@gmail.com
    # from email name
          from: Artem
