name: Ruby

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run tests
      run: |
       bundle init
       bundle add sorted_set

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.4.3.1']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      run: |
        choco install ruby --version 3.4.3.1 -y
        choco install msys2 -y
    - name: Run tests
      run: |
       bundle init
       bundle add sorted_set       
